# Generated by Django 5.1.4 on 2025-11-25 06:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name="Father's Name")),
                ('alias', models.CharField(blank=True, help_text='Urfiyat / Nickname', max_length=100)),
                ('cnic', models.CharField(help_text='Format: 12345-1234567-1', max_length=15, unique=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accused_photos/')),
                ('address', models.TextField(default='Unknown')),
                ('crime_history', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Accused',
                'verbose_name_plural': 'Accused',
            },
        ),
        migrations.CreateModel(
            name='BailApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_alloted_by_self', models.BooleanField(default=False, verbose_name='Not alloted by self')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('section', models.CharField(max_length=100)),
                ('advocate_name', models.CharField(max_length=100)),
                ('order_with_picture', models.ImageField(blank=True, null=True, upload_to='bail_orders/', verbose_name='Order with picture attached')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('CONSTABLE', 'Constable'), ('HEAD_CONSTABLE', 'Head Constable'), ('ASI', 'Assistant Sub-Inspector (ASI)'), ('SI', 'Sub-Inspector (SI)'), ('INSPECTOR', 'Inspector'), ('SHO', 'SHO'), ('PI', 'PI'), ('DSP', 'DSP'), ('SSP', 'SSP')], default='SI', max_length=20)),
                ('phone_number', models.CharField(help_text='Phone No.', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BailSurety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Surety Name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='bail_surety_photos/')),
                ('bail_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sureties', to='core.bailapplication')),
            ],
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_no', models.CharField(blank=True, max_length=20, unique=True, verbose_name='FIR No.')),
                ('police_station', models.CharField(blank=True, max_length=100, verbose_name='Police Station')),
                ('criminal_case_no', models.CharField(blank=True, max_length=50, verbose_name='Criminal Case No.')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date_reported', models.DateField(default=django.utils.timezone.now, verbose_name='FIR Date (Enter Data)')),
                ('is_unknown_accused', models.BooleanField(default=False, verbose_name='Unknown Accused')),
                ('case_property_image', models.ImageField(blank=True, null=True, upload_to='case_property/', verbose_name='Case Property Image (Evidence)')),
                ('description', models.TextField(blank=True, verbose_name='Description / OCR Text')),
                ('personal_search_item', models.TextField(blank=True, verbose_name='Personal Search Item')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INTERIM', 'Interim'), ('CHALLAN', 'Challan'), ('FINAL_REPORT', 'Final Report'), ('A_CLASS', 'A-Class'), ('SOLVED', 'Case Solved'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('accuseds', models.ManyToManyField(blank=True, to='core.accused', verbose_name='Select Accused')),
                ('officer_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.policeofficer', verbose_name='Investigating Officer (I/O)')),
            ],
            options={
                'verbose_name': 'FIR',
                'verbose_name_plural': 'FIRS',
            },
        ),
        migrations.AddField(
            model_name='bailapplication',
            name='fir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_applications', to='core.fir'),
        ),
        migrations.CreateModel(
            name='Remand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('accused_name', models.CharField(max_length=100)),
                ('io_name', models.CharField(max_length=100, verbose_name='I/O Name')),
                ('section_count', models.CharField(max_length=100, verbose_name='Section (count)')),
                ('order_copy', models.ImageField(blank=True, null=True, upload_to='remand_orders/', verbose_name='Order copy attached')),
                ('remand_type', models.CharField(choices=[('POLICE', 'Police'), ('JUDICIAL', 'Judicial')], default='POLICE', max_length=10)),
                ('police_remand_details', models.TextField(blank=True, verbose_name='Details')),
                ('judicial_remand_image', models.ImageField(blank=True, null=True, upload_to='judicial_remand_images/', verbose_name='Remand Image')),
                ('fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remands', to='core.fir')),
            ],
        ),
    ]
