# Generated by Django 5.2.8 on 2025-11-22 05:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='criminals/')),
                ('address', models.TextField(default='Unknown')),
                ('crime_history', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('CONSTABLE', 'Constable'), ('ASI', 'Assistant Sub-Inspector (ASI)'), ('SI', 'Sub-Inspector (SI)'), ('INSPECTOR', 'Inspector'), ('SHO', 'SHO')], default='SI', max_length=20)),
                ('badge_number', models.CharField(help_text='Belt No.', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date_reported', models.DateField(default=django.utils.timezone.now, verbose_name='FIR Date')),
                ('is_unknown_suspect', models.BooleanField(default=False, verbose_name='Unknown Suspect')),
                ('fir_image', models.ImageField(blank=True, null=True, upload_to='fir_scans/')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Investigation'), ('SOLVED', 'Case Solved'), ('SNOOZED', 'Snoozed (Warning)'), ('EXPIRED', 'Expired Case')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('suspects', models.ManyToManyField(blank=True, to='core.criminal', verbose_name='Select Criminals')),
                ('officer_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.policeofficer', verbose_name='Investigating Officer')),
            ],
        ),
    ]
